title: ScalaMock Tutorial
description: A comprehensive guide to using ScalaMock - a native Scala mocking framework
theme: just-the-docs

url: https://eclypsium-ef.github.io
baseurl: "/Tutorial_ScalaMocks"

aux_links:
  Repository: https://github.com/eclypsium-ef/Tutorial_ScalaMocks
  ScalaMock Official Website: https://scalamock.org

# Enable search
search_enabled: true

# Optional settings
heading_anchors: true
color_scheme: light

# Stop using readme.md for index.html
readme_index:
  enabled: false
  remove_originals: false

mermaid:
  enabled: true
